pod "RPBorderlessSegmentedControl", :path => "../RPBorderlessSegmentedControl.podspec"

target "RPBorderlessSegmentedControlDemoTests" do
  pod "FBSnapshotTestCase", git: "git@github.com:RobotsAndPencils/ios-snapshot-test-case.git", branch: "OSXSupport"
end